name: WakaTime

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  wakatime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install WakaTime CLI
        run: |
          pip install wakatime

      - name: Run WakaTime CLI
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          wakatime --entity . --write
